version: '3.8'

services:
  church-newsletter:
    build: .
    ports:
      - "80:80"
    container_name: church-newsletter
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 